swagger: "2.0"
info:
  version: "1.0.0"
  title: BlueDelta-API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /users:
    get:
      description: Returns List of 'Users'
      # used as the method name of the controller
      operationId: users-List
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UsersListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - blue-delta-userPool-authorizer: []
    post:
      description: Adds a User
      operationId: users-Create
      parameters:
      - $ref: "#/parameters/User"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []

  /users/{userId}:
    delete:
      description: Deletes a User
      operationId: users-Delete
      parameters:
      - $ref: "#/parameters/UserId"
      responses:
        "200":
          description: Success
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []
    get:
      description: Returns a User
      operationId: users-Get
      parameters:
      - $ref: "#/parameters/UserId"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []
    post:
      description: Updates a User
      operationId: users-Update
      parameters:
      - $ref: "#/parameters/UserId"
      - $ref: "#/parameters/User"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []

  /users/{userId}/orders:
    get:
      description: Returns List of 'Orders' by 'User'
      operationId: orders-ListByUser
      parameters:
      - $ref: "#/parameters/UserId"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/OrdersListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - blue-delta-userPool-authorizer: []

  /orders:
    get:
      description: Returns List of 'Orders'
      operationId: orders-List
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/OrdersListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []
    post:
      description: Adds an Order
      operationId: order-Create
      parameters:
      - $ref: "#/parameters/Order"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Order"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []

  /orders/{orderId}:
    delete:
      description: Deletes an Order
      operationId: orders-Delete
      parameters:
      - $ref: "#/parameters/OrderId"
      responses:
        "200":
          description: Success
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []
    get:
      description: Returns an Order
      operationId: orders-Get
      parameters:
      - $ref: "#/parameters/OrderId"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Order"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []
    post:
      description: Updates an Order
      operationId: orders-Update
      parameters:
      - $ref: "#/parameters/OrderId"
      - $ref: "#/parameters/Order"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Order"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []

  /buttons:
    get:
      description: Returns List of 'Buttons'
      # used as the method name of the controller
      operationId: buttons-List
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ButtonsListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - blue-delta-userPool-authorizer: []
    post:
      description: Adds a Button
      operationId: buttons-Create
      parameters:
      - $ref: "#/parameters/Button"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Button"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []

  /buttons/{buttonId}:
    delete:
      description: Deletes a Button
      operationId: buttons-Delete
      parameters:
      - $ref: "#/parameters/ButtonId"
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []
    get:
      description: Returns a Button
      # used as the method name of the controller
      operationId: buttons-Get
      parameters:
      - $ref: "#/parameters/ButtonId"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Button"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - blue-delta-userPool-authorizer: []
    post:
      description: Updates a Button
      operationId: buttons-Update
      parameters:
      - $ref: "#/parameters/ButtonId"
      - $ref: "#/parameters/Button"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Button"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []

  /threads:
    get:
      description: Returns List of 'Threads'
      # used as the method name of the controller
      operationId: threads-List
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ThreadsListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []
    post:
      description: Adds a Thread
      operationId: threads-Create
      parameters:
      - $ref: "#/parameters/Thread"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Thread"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []

  /threads/{threadId}:
    delete:
      description: Deletes a Thread
      operationId: threads-Delete
      parameters:
      - $ref: "#/parameters/ThreadId"
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []
    get:
      description: Returns a Thread
      # used as the method name of the controller
      operationId: threads-Get
      parameters:
      - $ref: "#/parameters/ThreadId"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Thread"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []
    post:
      description: Updates a Thread
      operationId: threads-Update
      parameters:
      - $ref: "#/parameters/ThreadId"
      - $ref: "#/parameters/Thread"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Thread"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []

  /fabrics:
    get:
      description: Returns List of 'Fabrics'
      # used as the method name of the controller
      operationId: fabrics-List
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/FabricsListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []
    post:
      description: Adds a Fabric
      operationId: fabrics-Create
      parameters:
      - $ref: "#/parameters/Fabric"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Fabric"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []

  /fabrics/{fabricId}:
    delete:
      description: Deletes a Fabric
      operationId: fabrics-Delete
      parameters:
      - $ref: "#/parameters/FabricId"
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []
    get:
      description: Returns a Fabric
      # used as the method name of the controller
      operationId: fabrics-Get
      parameters:
      - $ref: "#/parameters/FabricId"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Fabric"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []
    post:
      description: Updates a Fabric
      operationId: fabrics-Update
      parameters:
      - $ref: "#/parameters/FabricId"
      - $ref: "#/parameters/Fabric"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Fabric"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []

  /ping:
    get:
      description: Unsecured ping
      operationId: ping-PingOperation
      responses:
        "200":
          description: Success
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
      - sigv4: []

parameters:
  User:
    in: "body"
    name: "body"
    required: true
    schema:
      $ref: "#/definitions/User"
  UserId:
    in: "path"
    name: "userId"
    required: true
    type: string
  Order:
    in: "body"
    name: "body"
    required: true
    schema:
      $ref: "#/definitions/Order"
  OrderId:
    in: "path"
    name: "orderId"
    required: true
    type: string
  Button:
    in: "body"
    name: "body"
    required: true
    schema:
      $ref: "#/definitions/Button"
  ButtonId:
    in: "path"
    name: "buttonId"
    required: true
    type: string
  Thread:
    in: "body"
    name: "body"
    required: true
    schema:
      $ref: "#/definitions/Thread"
  ThreadId:
    in: "path"
    name: "threadId"
    required: true
    type: string
  Fabric:
    in: "body"
    name: "body"
    required: true
    schema:
      $ref: "#/definitions/Fabric"
  FabricId:
    in: "path"
    name: "fabricId"
    required: true
    type: string
definitions:
  UsersListResponse:
    required:
    - items
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/User"

  User:
    type: object
    required:
    - identityId
    properties:
      identityId:
        type: string
      jeans:
        type: array
        items:
          $ref: "#/definitions/Jean"

  OrdersListResponse:
    required:
    - items
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/Order"

  Order:
    required:
    - userId
    properties:
      orderId:
        type: string
      userId:
        type: string
      orderItems:
        type: array
        items:
          $ref: "#/definitions/OrderItem"
      transaction:
        $ref: "#/definitions/Transaction"

  OrderItemsListResponse:
    required:
    - items
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/OrderItem"

  OrderItem:
    required:
    - jean
    properties:
      jean:
        $ref: "#/definitions/Jean"
      status:
        type: string
      tracking:
        type: string

  TransactionsListResponse:
    required:
    - items
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/Transaction"

  Transaction:
    properties:
      transactionId:
        type: string
      status:
        type: string

  ButtonsListResponse:
    required:
    - items
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/Button"

  Button:
    type: object
    required:
    - buttonId
    properties:
      buttonId:
        type: string
      name:
        type: string
      thumb:
        type: string
      layer:
        type: string

  FabricsListResponse:
    required:
    - items
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/Fabric"

  Fabric:
    required:
    - fabricId
    properties:
      fabricId:
        type: string
      name:
        type: string
      weight:
        type: integer
        format: int32
        minimum: 0
      description:
        type: string
      materials:
        type: string
      supplier:
        type: string

  ThreadsListResponse:
    required:
    - items
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/Thread"

  Thread:
    required:
    - threadId
    properties:
      threadId:
        type: string
      name:
        type: string
      thumb:
        type: string
      layer:
        type: string

  MeasurementsListResponse:
    required:
    - items
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/Measurement"
  
  Measurement:
    required:
    - measurementId
    properties:
      measurementId:
        type: string
      userId:
        type: string
      waist:
        type: number
        format: float
        minimum: 0.0
      leg:
        type: number
        format: float
        minimum: 0.0
      # TODO Add more measurement parameters
  
  JeansListResponse:
    required:
    - items
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/Jean"
          
  Jean:
    required:
    - jeanId
    properties:
      jeanId:
        type: string
      measurement:
        $ref: "#/definitions/Measurement"
      thread:
        $ref: "#/definitions/Thread"
      fabric:
        $ref: "#/definitions/Fabric"
      button:
        $ref: "#/definitions/Button"

  ErrorResponse:
    required:
      - message
      - type
    properties:
      message:
        type: string
      type:
        type: string
securityDefinitions:
  blue-delta-custom-authorizer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "custom"
  blue-delta-userPool-authorizer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "cognito_user_pools"
  sigv4:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "awsSigv4"
