/**
 * BlueDelta-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Measurement {
    waist?: number;

    seatDown?: number;

    seatRight?: number;

    rise?: number;

    fullRise?: number;

    thighUpperDown?: number;

    thighUpperRight?: number;

    thighMiddleDown?: number;

    thighMiddleRight?: number;

    thighLowerDown?: number;

    thighLowerRight?: number;

    outseam?: number;

    kneeUp?: number;

    kneeRight?: number;

    calfUp?: number;

    calfRight?: number;

    legOpening?: number;

    desiredFit?: number;

}
