/**
 * BlueDelta-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Button'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Button'));
  } else {
    // Browser globals (root is window)
    if (!root.BlueDeltaApi) {
      root.BlueDeltaApi = {};
    }
    root.BlueDeltaApi.ButtonsListResponse = factory(root.BlueDeltaApi.ApiClient, root.BlueDeltaApi.Button);
  }
}(this, function(ApiClient, Button) {
  'use strict';




  /**
   * The ButtonsListResponse model module.
   * @module model/ButtonsListResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ButtonsListResponse</code>.
   * @alias module:model/ButtonsListResponse
   * @class
   * @param items {Array.<module:model/Button>} 
   */
  var exports = function(items) {
    var _this = this;

    _this['items'] = items;
  };

  /**
   * Constructs a <code>ButtonsListResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ButtonsListResponse} obj Optional instance to populate.
   * @return {module:model/ButtonsListResponse} The populated <code>ButtonsListResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [Button]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Button>} items
   */
  exports.prototype['items'] = undefined;



  return exports;
}));


