/**
 * BlueDelta-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Jean'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Jean'));
  } else {
    // Browser globals (root is window)
    if (!root.BlueDeltaApi) {
      root.BlueDeltaApi = {};
    }
    root.BlueDeltaApi.OrderItem = factory(root.BlueDeltaApi.ApiClient, root.BlueDeltaApi.Jean);
  }
}(this, function(ApiClient, Jean) {
  'use strict';




  /**
   * The OrderItem model module.
   * @module model/OrderItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderItem</code>.
   * @alias module:model/OrderItem
   * @class
   * @param jean {module:model/Jean} 
   */
  var exports = function(jean) {
    var _this = this;

    _this['jean'] = jean;


  };

  /**
   * Constructs a <code>OrderItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderItem} obj Optional instance to populate.
   * @return {module:model/OrderItem} The populated <code>OrderItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('jean')) {
        obj['jean'] = Jean.constructFromObject(data['jean']);
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('tracking')) {
        obj['tracking'] = ApiClient.convertToType(data['tracking'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Jean} jean
   */
  exports.prototype['jean'] = undefined;
  /**
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {String} tracking
   */
  exports.prototype['tracking'] = undefined;



  return exports;
}));


