/**
 * BlueDelta-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Jean'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Jean'));
  } else {
    // Browser globals (root is window)
    if (!root.BlueDeltaApi) {
      root.BlueDeltaApi = {};
    }
    root.BlueDeltaApi.User = factory(root.BlueDeltaApi.ApiClient, root.BlueDeltaApi.Jean);
  }
}(this, function(ApiClient, Jean) {
  'use strict';




  /**
   * The User model module.
   * @module model/User
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   * @param identityId {String} 
   */
  var exports = function(identityId) {
    var _this = this;

    _this['identityId'] = identityId;

  };

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('identityId')) {
        obj['identityId'] = ApiClient.convertToType(data['identityId'], 'String');
      }
      if (data.hasOwnProperty('jeans')) {
        obj['jeans'] = ApiClient.convertToType(data['jeans'], [Jean]);
      }
    }
    return obj;
  }

  /**
   * @member {String} identityId
   */
  exports.prototype['identityId'] = undefined;
  /**
   * @member {Array.<module:model/Jean>} jeans
   */
  exports.prototype['jeans'] = undefined;



  return exports;
}));


