// Autogenerated file, do not modify directly
(function () {
  angular 
    .module('bdApp')
    .service('AWSConfig', AWSConfig);
      
  function AWSConfig () {
		return{
			"REGION": "us-east-1",
		  "PROFILE_IMAGES_S3_BUCKET": "blue-delta-api-development-stack-userdatabucket-12z57hiicf3xy",
		  "API_ENDPOINT": "https://kd6f1omjzc.execute-api.us-east-1.amazonaws.com/development",
		  "USER_POOL_ID": "us-east-1_UvVeNoe5z",
		  "CLIENT_ID": "6hdrpk1j20qmjhfdiga31uia80",
		  "IDENTITY_POOL_ID": "us-east-1:60250bd7-bc76-4ab7-8813-2369461cb881"
		}
  }


})();