/**
 * BlueDelta-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BlueDeltaApi);
  }
}(this, function(expect, BlueDeltaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BlueDeltaApi.Fabric();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Fabric', function() {
    it('should create an instance of Fabric', function() {
      // uncomment below and update the code to test Fabric
      //var instane = new BlueDeltaApi.Fabric();
      //expect(instance).to.be.a(BlueDeltaApi.Fabric);
    });

    it('should have the property fabricId (base name: "fabricId")', function() {
      // uncomment below and update the code to test the property fabricId
      //var instane = new BlueDeltaApi.Fabric();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new BlueDeltaApi.Fabric();
      //expect(instance).to.be();
    });

    it('should have the property weight (base name: "weight")', function() {
      // uncomment below and update the code to test the property weight
      //var instane = new BlueDeltaApi.Fabric();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new BlueDeltaApi.Fabric();
      //expect(instance).to.be();
    });

    it('should have the property materials (base name: "materials")', function() {
      // uncomment below and update the code to test the property materials
      //var instane = new BlueDeltaApi.Fabric();
      //expect(instance).to.be();
    });

    it('should have the property supplier (base name: "supplier")', function() {
      // uncomment below and update the code to test the property supplier
      //var instane = new BlueDeltaApi.Fabric();
      //expect(instance).to.be();
    });

  });

}));
