/**
 * BlueDelta-API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BlueDeltaApi);
  }
}(this, function(expect, BlueDeltaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BlueDeltaApi.Measurement();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Measurement', function() {
    it('should create an instance of Measurement', function() {
      // uncomment below and update the code to test Measurement
      //var instane = new BlueDeltaApi.Measurement();
      //expect(instance).to.be.a(BlueDeltaApi.Measurement);
    });

    it('should have the property measurementId (base name: "measurementId")', function() {
      // uncomment below and update the code to test the property measurementId
      //var instane = new BlueDeltaApi.Measurement();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new BlueDeltaApi.Measurement();
      //expect(instance).to.be();
    });

    it('should have the property waist (base name: "waist")', function() {
      // uncomment below and update the code to test the property waist
      //var instane = new BlueDeltaApi.Measurement();
      //expect(instance).to.be();
    });

    it('should have the property leg (base name: "leg")', function() {
      // uncomment below and update the code to test the property leg
      //var instane = new BlueDeltaApi.Measurement();
      //expect(instance).to.be();
    });

  });

}));
